# Generated by Django 2.2.4 on 2019-08-19 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagtable', '0002_auto_20190721_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['-svn_revision']},
        ),
        migrations.AlterModelOptions(
            name='releasenotedata',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-release_time', '-name']},
        ),
        migrations.AlterField(
            model_name='commit',
            name='git_hash',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]{40}$')]),
        ),
    ]
