# Generated by Django 2.2.4 on 2019-09-25 12:51

from django.db import migrations, models
import django.db.models.deletion


def create_branch(apps, schema_editor):
    Branch = apps.get_model("tagtable", "Branch")
    Tag = apps.get_model("tagtable", "Tag")
    for tag in Tag.objects.all():
        branch = Branch.objects.get_or_create(name=tag.branch)[0]
        branch.save()
        tag.branch_new = branch
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tagtable', '0003_auto_20190819_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('obsolete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='branch_new',
            field=models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tagtable.Branch'),
            preserve_default=False,
        ),
        migrations.RunPython(create_branch),
    ]
