# Generated by Django 2.2.4 on 2019-09-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('tagtable', '0005_auto_20190925_1313'), ('tagtable', '0006_auto_20190925_1314'), ('tagtable', '0007_remove_tag_branch_old')]

    dependencies = [
        ('tagtable', '0004_auto_20190925_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='branch',
            new_name='branch_old',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='branch_new',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='branch_old',
        ),
    ]
